// Code generated by "stringer -type=LineType"; DO NOT EDIT.

package esoelog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BeginLog-0]
	_ = x[EndLog-1]
	_ = x[BeginCombat-2]
	_ = x[EndCombat-3]
	_ = x[PlayerInfo-4]
	_ = x[BeginCast-5]
	_ = x[EndCast-6]
	_ = x[CombatEvent-7]
	_ = x[HealthRegen-8]
	_ = x[UnitAdded-9]
	_ = x[UnitChanged-10]
	_ = x[UnitRemoved-11]
	_ = x[EffectChanged-12]
	_ = x[AbilityInfo-13]
	_ = x[EffectInfo-14]
	_ = x[MapChanged-15]
	_ = x[ZoneChanged-16]
	_ = x[TrialInit-17]
	_ = x[BeginTrial-18]
	_ = x[EndTrial-19]
	_ = x[firstLineType-0]
}

const _LineType_name = "BeginLogEndLogBeginCombatEndCombatPlayerInfoBeginCastEndCastCombatEventHealthRegenUnitAddedUnitChangedUnitRemovedEffectChangedAbilityInfoEffectInfoMapChangedZoneChangedTrialInitBeginTrialEndTrial"

var _LineType_index = [...]uint8{0, 8, 14, 25, 34, 44, 53, 60, 71, 82, 91, 102, 113, 126, 137, 147, 157, 168, 177, 187, 195}

func (i LineType) String() string {
	if i < 0 || i >= LineType(len(_LineType_index)-1) {
		return "LineType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LineType_name[_LineType_index[i]:_LineType_index[i+1]]
}
